apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app.storage_name }} 
  namespace: personal
spec:
  storageClassName: nfs-csi-hdd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.app.storage_amount }}